name: CI

on:
    pull_request:
    push:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Default to bash
defaults:
    run:
        shell: bash

jobs:
    # Lint job
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint

    # Test job
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test:coverage
            - name: Upload Code Coverage
              uses: codecov/codecov-action@v3.1.0
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
    # Build job
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run build
              run: npm run build
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: zohar-build
                  path: ./dist
    # Check exports job
    check-exports:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Dounload build artifact
              uses: actions/download-artifact@v4
              with:
                  path: ./dist
                  name: zohar-build
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run check exports
              run: npm run check-exports
